# -*- coding: utf-8 -*-
"""ML ACTIVITY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr_IpwF46i1m3Vy0P4TKvD2j7Msg-Mzi
"""

import gradio as gr
from sklearn import tree

# Define the features and labels
features = [[0, 1, 0], [0, 1, 0], [1, 1, 1], [0, 1, 1], [1, 0, 0]]
labels = ["TCC", "CC", "TCC", "CC", "cc"]

# Train the decision tree classifier
myClassifier = tree.DecisionTreeClassifier()
myModel = myClassifier.fit(features, labels)

# Create the Gradio interface
inputs = [gr.Number(label="Feature 1"), gr.Number(label="Feature 2"), gr.Number(label="Feature 3")]
outputs = gr.Textbox(label="Prediction")

gr.Interface(fn=lambda f1, f2, f3: myModel.predict([[f1, f2, f3]])[0],
             inputs=inputs,
             outputs=outputs,
             title="Decision Tree Classifier",
             description="Predict the label based on the features").launch()